### 1. Crear un Pedido Nuevo
POST http://localhost:3000/api/pedidos
Content-Type: application/json

{
  "usuarioId": 1,
  "items": [
    {
      "productoId": 3,
      "cantidad": 1
    }
  ]
}

### 2. Ver todos los pedidos (Para comprobar que se guardó)
GET http://localhost:3000/api/pedidos


### 3. Elimina el producto con id especifico
DELETE http://localhost:3000/api/productos/46

### 4. Crear Usuario CLIENTE (Sin código)
POST http://localhost:3000/api/usuarios
Content-Type: application/json

{
  "nombreCompleto": "Pedro Cliente",
  "email": "pedro@example.com",
  "password": "12345",
  "rol": "CLIENTE"
}

### 5. Ver usuarios
GET http://localhost:3000/api/usuarios/users


### 6. Crear Usuario TUTOR (Con código obligatorio)
POST http://localhost:3000/api/usuarios
Content-Type: application/json

{
  "nombreCompleto": "Profe Garcia",
  "email": "profe@example.com",
  "password": "123",
  "rol": "TUTOR",
  "codigoTutor": "PROF-2024"
}

### 7. Login de usuario
POST http://localhost:3000/api/usuarios/login
Content-Type: application/json

{
  "email": "pedro@example.com",
  "password": "12345"
}